name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ROS 2 Humble
      uses: ros-tooling/setup-ros@v0.2.1
      with:
        distribution: humble

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-colcon-common-extensions python3-pip
        pip3 install -U empy

    - name: Install package dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ros-humble-rclcpp \
          ros-humble-std-msgs \
          ros-humble-ament-cmake \
          ros-humble-ament-lint-auto \
          ros-humble-ament-cmake-gtest

    - name: Build the workspace
      run: |
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release

    - name: Run tests
      run: |
        colcon test --event-handlers console_cohesion+

    - name: Test result
      run: |
        colcon test-result --verbose
