name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Uninstall conflicting 'em' package
      run: |
        pip uninstall -y em

    - name: Install empy
      run: |
        pip install empy

    - name: Set up ROS 2
      uses: ros-tooling/setup-ros@0.7.1
      with:
        required-ros-distributions: humble

    - name: Run ROS CI
      uses: ros-tooling/action-ros-ci@0.3.5

    - name: Install dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install -y python3-colcon-common-extensions python3-pip
        sudo apt-get install -y \
          ros-humble-rclcpp \
          ros-humble-std-msgs \
          ros-humble-ament-cmake \
          ros-humble-ament-lint-auto \
          ros-humble-ament-cmake-gtest

    - name: Build the workspace
      run: |
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release

    - name: Run tests
      run: |
        colcon test --event-handlers console_cohesion+

    - name: Test result
      run: |
        colcon test-result --verbose
